#Automatically generated by pip2arch on 2011-01-16
#Mainainer: Buce <dmbuce@gmail.com>

pkgname=python-nbt
pkgver=1.3.0
pkgrel=0
pkgdesc="Named Binary Tag Reader/Writer"
url="http://github.com/twoolie/NBT"
depends=('python')
makedepends=('python-distribute' 'unzip')
license=('CUSTOM')
arch=('any')
#source=('http://pypi.python.org/packages/source/N/NBT/NBT-$pkgver.zip')
source=("$pkgname-$pkgver.zip::https://github.com/twoolie/NBT/zipball/version-$pkgver")
md5sums=('76c2e16b415b127409db3ed9fe0f4ea4')

build() {
    #cd "$srcdir/NBT-$pkgver"
    cd "$srcdir/$(zipinfo -1 "$srcdir/$pkgname-$pkgver.zip" | head -1)"
    python setup.py install --root="$pkgdir" --optimize=1
}

# vim: set ts=4 sw=4 et:
